language: R
sudo: false
cran: http://cran.rstudio.com
cache: packages
warnings_are_errors: false
os:
  - linux
  - osx

r_build_args: "--no-manual --no-build-vignettes"
r_check_args: "--as-cran --ignore-vignettes --no-examples --install-args=--build"

before_install:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}
  - cat DESCRIPTION
  - export PACKAGE_NAME=`package_name`
  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck

after_success:
  - cat ${RCHECK_DIR}/00install.out
  - cat ${RCHECK_DIR}/00check.log

after_failure:
  - cat ${RCHECK_DIR}/00install.out
  - cat ${RCHECK_DIR}/00check.log

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
      PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
      mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1);
      PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
      mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
    fi
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]];
    then
      rm -f *.tar.gz;
    fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: dQlTu6TqCFGzvFzPRtxM8jYxZM0RIdBTHq/CnPMSDNuy2vToRNFQGrzCUfPcWLjDgrp7KRIJ+lvx+VghzFeIODnEKEdplLR3QCqOFWFa5KyxC4Oaq0pdn0fAjOadeFmLiakvxBCsC7LeOlMZLS5OdJIxpLNO2hqSNoHjKxFMWKU2m9Eh1CsCVa4JzHV9omomrmRrF1BkuJp63+mMfVvyS800AQPIAD/VIY6PjGJRf0a4nf7ux3oUGrE2nt2DzW/O4iGdXMs09Kcut21xK6W291ncBpGi07kVXlCCtpqGudKXHnXRF6yvz/P/KqhmBkMTmS6qBvGhjLEshiLZsVlaiyX8l9tesM3mbJxq2f5C8If5VrBD271afnawgFDh2+A1G1i0K2GK0IXY85viaBQ1Us+LRi7rRLvosjqi5w1xSAHJwMxO7ffKcgiQxWJxv8dqbDHACzzE5QxpgwkVJ62/lu0rEv45X6/6AeSzTkBkKRF9GjK/kYDhgtimXq6DrkXyLYikkLh3Q/ZBSA/emqIJAuzBe5Lj+FPg/qkHrDTx0CPLCkgGGFoJr8Rupvg8K43QwRLQIZ5dzeCUt1m1077c08RSCNnxsy4RPNG9FKpjsJkCIxLF4LQJlwwUw/bRCG4CiwvfxyBTyazpw5/hOteMUmm/Gpd4lc59gM4hyKaGhyg=
  file_glob: true
  file: ${PACKAGE_NAME}*.t*gz
  on:
    repo: swarm-lab/${PACKAGE_NAME}
    tags: true
