language: R
sudo: false
cran: http://cran.rstudio.com
cache: packages
warnings_are_errors: true
os:
  - linux
  - osx

r_build_args: "--no-manual --no-build-vignettes"
r_check_args: "--as-cran --ignore-vignettes --no-examples --install-args=--build"

before_install:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}
  - cat DESCRIPTION
  - export PACKAGE_NAME=`package_name`
  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck

apt_packages:
  - libgdal-dev
  - libudunits2-dev
  - libssh2-1-dev
  - imagemagick
  - cargo
  - libavformat-dev
  - libavcodec-dev
  - libavfilter-dev
  - libmagick++-dev
  - libgsl-dev

addons:
  homebrew:
    packages:
    - gsl

after_success:
  - cat ${RCHECK_DIR}/00install.out
  - cat ${RCHECK_DIR}/00check.log

after_failure:
  - cat ${RCHECK_DIR}/00install.out
  - cat ${RCHECK_DIR}/00check.log

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
      PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
      mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1);
      PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
      mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
    fi
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]];
    then
      rm -f *.tar.gz;
    fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: d2Xd7nrXw6b8TVYyBM9Kt1H0XdC2K4UMxoXcSTsNe3jit8Qa09v6A+PBwrdsYClNyVnWUIm+w6BwD7E4vWqxJM0CcZiBi3did4GTBm02TbJ9MbQbPIFZ5c8n230scYlADi28k4jH1hafM0egEHTDiFG3nHqZJFEKk/hi3KHZwPLzPrMobFCYqVa9zLopAIuKWY1D4JXTynnM5Dn+pAcEbgG1w6+fQHgacJBwFqUUhmGYdolHaLO5BrQEFa5eFzpiCLVED1BB3AyIYgyOFJ4MAHhrz8OHdmMmrGWRWm3e+OIgLa57FxbAkJ3rCmR1IFdOFNmIjQlEOQ91CxoUPhVR+cTXClKI+NmvpYZIhNIWoTaFvLS1rRRflSXUxmMKF5Btzs3sVfpqyUjJIH5YBCh1Damp2PKNjcVR3fF90V9YnDHrnM5PeBxEXszFWaWOtQ1Vlcm5C39IEcGa15NVJQ/hXgoYU4t4iS5rewJsbuq0Z7CS4RoqBaSlIg1aPny1KR6EAsjjgQTmBpFih5N+7pJu1vQ6Fhy9nGH4tHthIi0Ul98zIllRkJa2ex8FcwmX4AhHNEc+p+o4Whj8uWMNfu45vo4Fm3osT4aHpFRa9tJr3Ij240ERIHzYqwvsQd22uyTp9sEPTLxS4RchowojIkhGZgr7n3wRRpO0frzQ3oFHj5E=
  file_glob: true
  file: ${PACKAGE_NAME}*.t*gz
  on:
    repo: swarm-lab/${PACKAGE_NAME}
    tags: true
